airflow:
  dag_id: silver_dbt
  owner: airflow
  start_date: 2024-01-01
  schedule_interval: '@weekly'
  tags:
    - silver
    - fct
    - dim
    - ref

tasks:
  - task_id: collect_dbt_job_id
    operator: airflow.operators.python.PythonOperator
    params:
      python_callable: hooks.dbt.get_dbt_job_id
      op_kwargs:
        dbt_cloud_conn_id: dbt_jhg
        job_name: 'Build Bronze Silver'

  - task_id: build_b2_b3
    operator: airflow.providers.dbt.cloud.operators.dbt.DbtCloudRunJobOperator
    params:
      dbt_cloud_conn_id: dbt_jhg
      job_id: '{{ ti.xcom_pull(task_ids="collect_dbt_job_id") }}'
    upstream:
      - collect_dbt_job_id

